import BananaBread from '../assets/banana-bread.jpeg';
import Biscuits from '../assets/biscuits.jpeg';
import BroccoliSoup from '../assets/broccoli-soup.jpeg';
import ChickenLeg from '../assets/chicken-leg.jpeg';
import ChickenPastaBowl from '../assets/chicken-pasta-bowl.jpeg';
import ChickenPasta from '../assets/chicken-pasta.jpeg';
import Fish from '../assets/fish.jpeg';
import FrenchOnion from '../assets/french-onion.jpeg';
import FriedChicken from '../assets/fried-chicken.jpeg';
import Hoogie from '../assets/hoogie-steak-and-cheese.jpeg';
import PotatoSoup from '../assets/potato-soup.jpeg';
import PumpkinChocolate from '../assets/pumpkin-chocolate.jpeg';
import Snikerdoodles from '../assets/snikerdoodles.jpeg';
import StuffedPeppers from '../assets/stuffed-peppers.jpeg';


export const DinnerList = [
    {
        name: "Tortellini Soup",
        image: "",
        prepTime: "Prep Time 20min",
        cookTime: "Cook Time 8h",
        time: "Total Time 8h 20min",
        servings: "6",
        ingredients1:"1 package (17.6 ounces) - Italian Sausage",
        ingredients2:"1/2 Medium Onion",
        ingredients3:"4 Cloves Garlic Minced",
        ingredients4:"1 can (28 fluid ounces) - Can Crushed Tomatoes",
        ingredients5:"1 can (14 fluid ounces) - Can Diced Tomatoes w/ Juice",
        ingredients6:"4 cups - Chicken Broth",
        ingredients7:"2 packages (9 ounce) Refrigerated Cheese Tortellini",
        ingredients8:"3/4 cup - Heavy/Whipping Cream",
        ingredients9:"2 cupps - Fresh Baby Spinach",
        ingredients10: "Salt and Pepper",
        instructions1: "Take your sausages out of their casings and crumble into skillet. Add the chopped onion, saute for about 7 minutes. Add garlic in towards the end. Spoon out most of the fat, add the sausage mixture to the crockpot.",
        instructions2: "Add all ingredients to crockpot EXCEPT the tortellini, spinach, cream, salt, and pepper. 7-8 hours on low or 4-5 hours on high.",
        instructions3: "About 30 minutes before serving add the tortellini, cream, and spinach, then put on high if not already, Stir occasianlly then season with salt and pepper before serving.",
        byWho:"By: Natasha"

    },
    {
        name: "BBQ Chicken Leg",
        image: ChickenLeg,
        prepTime: "20min",
        cookTime: "30min",
        time: 4.99,
        servings: "",
        ingredients1:"Chicken Legs",
        ingredients2:"BBQ Sauce",
        ingredients3:"Salt",
        ingredients4:"Pepper",
        ingredients5:"here",
        ingredients6:"here",
        ingredients7:"here",
        ingredients8:"here",
        ingredients9:"here",
        instructions: "Mollit in consectetur nostrud aliqua ut non id non proident officia labore sunt amet adipisicing. Reprehenderit cillum dolor aute quis sit ex ex et irure fugiat ad duis nostrud veniam. Deserunt officia aliqua laboris irure consectetur id irure dolor do adipisicing.",
        byWho:""
    },
    {
        name: "Banana Bread",
        image: BananaBread,
        prepTime: "20min",
        cookTime: "30min",
        time: 4.99,
        servings: "",
        ingredients1:"Old Bananas",
        ingredients2:"Flour",
        ingredients3:"Baking Powder",
        ingredients4:"Chocolate Chips",
        ingredients5:"here",
        ingredients6:"here",
        ingredients7:"here",
        ingredients8:"here",
        ingredients9:"here",
        instructions: "Labore eiusmod pariatur esse commodo commodo duis nostrud consequat dolor mollit adipisicing ipsum laborum elit. Deserunt in voluptate voluptate sunt proident aute eiusmod minim mollit amet tempor. Commodo adipisicing occaecat cillum irure labore quis cupidatat est labore nostrud do minim exercitation ad. Ea consequat cupidatat fugiat proident ut ex ut sit dolore ipsum officia eiusmod ipsum est.",
        byWho:""
    },

    {
        name: "Biscuits",
        image: Biscuits,
        prepTime: "20min",
        cookTime: "30min",
        time: 4.99,
        servings: "",
        ingredients1:"Flour",
        ingredients2:"Baking Powder",
        ingredients3:"here",
        ingredients4:"here",
        ingredients5:"here",
        ingredients6:"here",
        ingredients7:"here",
        ingredients8:"here",
        ingredients9:"here",
        instructions: "Labore eiusmod pariatur esse commodo commodo duis nostrud consequat dolor mollit adipisicing ipsum laborum elit. Deserunt in voluptate voluptate sunt proident aute eiusmod minim mollit amet tempor. Commodo adipisicing occaecat cillum irure labore quis cupidatat est labore nostrud do minim exercitation ad. Ea consequat cupidatat fugiat proident ut ex ut sit dolore ipsum officia eiusmod ipsum est.",
        byWho:""
    },

    {
        name: "Broccoli Soup",
        image: BroccoliSoup,
        prepTime: "20min",
        cookTime: "30min",
        time: 4.99,
        servings: "",
        ingredients1:"Broccoli",
        ingredients2:"Cheddar Cheese",
        ingredients3:"here",
        ingredients4:"here",
        ingredients5:"here",
        ingredients6:"here",
        ingredients7:"here",
        ingredients8:"here",
        ingredients9:"here",
        instructions: "Labore eiusmod pariatur esse commodo commodo duis nostrud consequat dolor mollit adipisicing ipsum laborum elit. Deserunt in voluptate voluptate sunt proident aute eiusmod minim mollit amet tempor. Commodo adipisicing occaecat cillum irure labore quis cupidatat est labore nostrud do minim exercitation ad. Ea consequat cupidatat fugiat proident ut ex ut sit dolore ipsum officia eiusmod ipsum est.",
        byWho:""
    },

    {
        name: "Chicken Pasta Bowl",
        image: ChickenPastaBowl,
        prepTime: "20min",
        cookTime: "30min",
        time: 4.99,
        servings: "",
        ingredients1:"Chicken Thighs",
        ingredients2:"Shredded Mozzarella",
        ingredients3:"here",
        ingredients4:"here",
        ingredients5:"here",
        ingredients6:"here",
        ingredients7:"here",
        ingredients8:"here",
        ingredients9:"here",
        instructions: "Labore eiusmod pariatur esse commodo commodo duis nostrud consequat dolor mollit adipisicing ipsum laborum elit. Deserunt in voluptate voluptate sunt proident aute eiusmod minim mollit amet tempor. Commodo adipisicing occaecat cillum irure labore quis cupidatat est labore nostrud do minim exercitation ad. Ea consequat cupidatat fugiat proident ut ex ut sit dolore ipsum officia eiusmod ipsum est.",
        byWho:""
    },

    {
        name: "Chicken Pasta",
        image: ChickenPasta,
        prepTime: "20min",
        cookTime: "30min",
        time: 4.99,
        servings: "",
        ingredients1:"Chicken Thighs",
        ingredients2:"Shredded Mozzarella",
        ingredients3:"here",
        ingredients4:"here",
        ingredients5:"here",
        ingredients6:"here",
        ingredients7:"here",
        ingredients8:"here",
        ingredients9:"here",
        instructions: "Labore eiusmod pariatur esse commodo commodo duis nostrud consequat dolor mollit adipisicing ipsum laborum elit. Deserunt in voluptate voluptate sunt proident aute eiusmod minim mollit amet tempor. Commodo adipisicing occaecat cillum irure labore quis cupidatat est labore nostrud do minim exercitation ad. Ea consequat cupidatat fugiat proident ut ex ut sit dolore ipsum officia eiusmod ipsum est.",
        byWho:""
    },

    {
        name: "Fish",
        image: Fish,
        prepTime: "20min",
        cookTime: "30min",
        time: 4.99,
        servings: "",
        ingredients1:"Halubet",
        ingredients2:"here",
        ingredients3:"here",
        ingredients4:"here",
        ingredients5:"here",
        ingredients6:"here",
        ingredients7:"here",
        ingredients8:"here",
        ingredients9:"here",
        instructions: "Labore eiusmod pariatur esse commodo commodo duis nostrud consequat dolor mollit adipisicing ipsum laborum elit. Deserunt in voluptate voluptate sunt proident aute eiusmod minim mollit amet tempor. Commodo adipisicing occaecat cillum irure labore quis cupidatat est labore nostrud do minim exercitation ad. Ea consequat cupidatat fugiat proident ut ex ut sit dolore ipsum officia eiusmod ipsum est.",
        byWho:""
    },

    {
        name: "French Onion",
        image: FrenchOnion,
        prepTime: "20min",
        cookTime: "30min",
        time: 4.99,
        servings: "",
        ingredients1:"Onions",
        ingredients2:"Mozzarella",
        ingredients3:"Bread",
        ingredients4:"here",
        ingredients5:"here",
        ingredients6:"here",
        ingredients7:"here",
        ingredients8:"here",
        ingredients9:"here",
        instructions: "Labore eiusmod pariatur esse commodo commodo duis nostrud consequat dolor mollit adipisicing ipsum laborum elit. Deserunt in voluptate voluptate sunt proident aute eiusmod minim mollit amet tempor. Commodo adipisicing occaecat cillum irure labore quis cupidatat est labore nostrud do minim exercitation ad. Ea consequat cupidatat fugiat proident ut ex ut sit dolore ipsum officia eiusmod ipsum est.",
        byWho:""
    },

    {
        name: "Fried Chicken",
        image: FriedChicken,
        prepTime: "Prep Time 20min",
        cookTime: "Cook Time 30min",
        time: "Total Time 50min",
        heat: "Heat 375\u00b0F",
        servings: "24 Servings",
        ingredients1:"4 - Chicken Thighs/Breasts",
        ingredients2:"1 tsp - Onion Powder",
        ingredients3:"2 - Eggs",
        ingredients4:"1 tsp - Baking Powder",
        ingredients5:"2 tsp - Pepper",
        ingredients6:"2 tbsp - Brown Sugar",
        ingredients7:"1/2 tsp - Cayenne Pepper",
        ingredients8:"2 cups - Cornstarch",
        ingredients9:"1 cup - Flour",
        ingredients10:"1 tbsp - Garlic Salt",
        ingredients11:"1 tsp - Paprika",
        ingredients12:"1 tsp - Salt",
        ingredients13:"2 2/3 - Soybean or Canola or Vegetable Oil",
        ingredients14:"3/4 cup - Water",
        instructions1: "Cut each chicken breast/thigh into 4-6 strips. Prepare the breading and batter into two separate bowls.",
        instructions2: "Dip each piece of chicken into the breading then into the wet batter and then into the breading again. Shake off excess flour and repeat with the other chicken pieces.",
        instructions3: "In a large pot or dutch oven heat oil to 350\u00b0F. Fry chicken in small batches for 6 minutes or until golden brown. Serve with your favorite dipping sauce.",
        byWho:"By: Alyona Demyanchuk"
    },

    {
        name: "French Dip Sandwiches",
        image: Hoogie,
        prepTime: "20min",
        cookTime: "30min",
        time: "4hrs 10min",
        heat: "Crockpot",
        servings: "8  servings",
        ingredients1:"3 lbs - Beef, Steak or Roast",
        ingredients2:"1 tsp - Garliv Powder",
        ingredients3:"2 tsp - Onion Powder",
        ingredients4:"1 package - Au jus Gravy Mix",
        ingredients5:"1 packet - Gravy Mix, Brown",
        ingredients6:"8 Hoagie Rolls",
        ingredients7:"1 Butter",
        ingredients8:"8 Provolone Cheese, Slices",
        ingredients9:"2 Cups Water",
        instructions1: "Place the sliced beef, onion powder, garlic powder, au jus mix, brown gravy mix, and water into the crockpot, Cook on HIGH for 4 hours, or LOW for 6-8 hours.",
        instructions2: "Broil buns for 1-2 minutes, then add beef and cheese and broil 1-2 minute.",
        instructions3: "Serve with sauce from the crockpot on the side.",
        byWho:"By: Diana"
    },

    {
        name: "Potato Soup",
        image: PotatoSoup,
        prepTime: "Prep Time 15min",
        cookTime: "Cook Time 40min",
        time: "Total Time 55min",
        heat: "N/A",
        servings: "6 Servings",
        ingredients1:"6 Strips - Bacon",
        ingredients2:"1/2 Medium Onio",
        ingredients3:"4 Large Potatoes",
        ingredients4:"1/4 cup - Flour",
        ingredients5:"4 cups - Whole Milk",
        ingredients6:"1 cup - Chicken Broth",
        ingredients7:"1 Clove Minced Garlic",
        ingredients8:"3/4 cup - Grated Chedder Cheese",
        ingredients9:"To Taste - Chopped Scallions",
        ingredients10: "3/4 cup - Sour Cream",
        ingredients11: "Salt",
        ingredients12: "Pepper",
        instructions1: "Cut up the bacon and add it to a soup pot. Fry the bacon over medium-high heat until it's nice and crispy",
        instructions2: "Meanwhile, prep your onion and potatoes. Can peel or unpeel potatoes.",
        instructions3: "Once the bacon is done, take it out of the pot and transfer to a paper towel lined plate. Leave about 2 tbsp of the bacon fat in the pot.",
        instructions4: "Add onion to the pot and saute it for 5 minutes.",
        instructions5: "Stir in the flour and cook for about a minute.",
        instructions6: "Whisk the milk in slowly until the flour has dissolved.",
        instructions7: "Add the chicken broth, garlic, and potatoes. Increase the heat to high. Scrape up pot. When the soup is almost boiling, reduce the heat and cover the pot with the lid slightly open. Let the soup simmer gently for 20 minutes.",
        instructions8: "The potatoes should be quite fall-apart tender. Can smashed potatoes or leave them.",
        instructions9: "Stir in the sour creamand most of the cheddar and bacon, reserve some for the top, season the soup with salt and pepper.",
        byWho:"By: Natasha"
    },

    {
        name: "Pumpkin Chocolate Cookie",
        image: PumpkinChocolate,
        prepTime: "20min",
        cookTime: "30min",
        time: 4.99,
        servings: "",
        ingredients1:"Pumkin Spread",
        ingredients2:"Chocolate Chips",
        ingredients3:"Flour",
        ingredients4:"here",
        ingredients5:"here",
        ingredients6:"here",
        ingredients7:"here",
        ingredients8:"here",
        ingredients9:"here",
        instructions: "Labore eiusmod pariatur esse commodo commodo duis nostrud consequat dolor mollit adipisicing ipsum laborum elit. Deserunt in voluptate voluptate sunt proident aute eiusmod minim mollit amet tempor. Commodo adipisicing occaecat cillum irure labore quis cupidatat est labore nostrud do minim exercitation ad. Ea consequat cupidatat fugiat proident ut ex ut sit dolore ipsum officia eiusmod ipsum est.",
        byWho:""
    },

    {
        name: "Snikerdoodle",
        image: Snikerdoodles,
        prepTime: "20min",
        cookTime: "30min",
        time: 4.99,
        servings: "",
        ingredients1:"Snikerdoodle",
        ingredients2:"Flour",
        ingredients3:"here",
        ingredients4:"here",
        ingredients5:"here",
        ingredients6:"here",
        ingredients7:"here",
        ingredients8:"here",
        ingredients9:"here",
        instructions: "Labore eiusmod pariatur esse commodo commodo duis nostrud consequat dolor mollit adipisicing ipsum laborum elit. Deserunt in voluptate voluptate sunt proident aute eiusmod minim mollit amet tempor. Commodo adipisicing occaecat cillum irure labore quis cupidatat est labore nostrud do minim exercitation ad. Ea consequat cupidatat fugiat proident ut ex ut sit dolore ipsum officia eiusmod ipsum est.",
        byWho:""
    },
    {
        name: "Stuffed Peppers",
        image: StuffedPeppers,
        prepTime: "Prep Time 10min",
        cookTime: "Cook Time 45min",
        time: "Total Time 55min",
        heat: "Heat 375\u00b0F",
        servings: "4 Servings",
        ingredients1:"1 lb - Hot Italian Sausage",
        ingredients2:"2 tbsp - Olive Oil",
        ingredients3:"1 cup - White Rice",
        ingredients4:"14 ounces - Fire Roasted Diced Tomatoes",
        ingredients5:"3 - Cloves Garlic",
        ingredients6:"1/2 - Yellow Onion",
        ingredients7:"4 - Bell Peppers",
        ingredients8:"1/2 cup - Chicken Broth",
        ingredients9:"1/2 tsp - Dried Oregano",
        ingredients10: "1/2 tsp - Dried Basil",
        ingredients11: "1/2 tsp - Dried Thyme",
        ingredients12: "1/2 tsp - Crushed Red Pepper Flakes",
        ingredients13: "1 tsp - Salt",
        ingredients14: "1 tsp - Worcestershire Sauce",
        ingredients15: "1/2 tsp - Pepper",
        ingredients16: "1/4 cup - Italian Blend Shredded Cheese",
        ingredients17: "Garnish Fresh Italian Flat Leaf Parsley",
        instructions1: "Cook rice according to package instructions, do not overcook, better to be a tad al dente because you'll be putting into the oven.",
        instructions2: "In a large saute pan over medium high heat, add 2 tbsp olive oil and the hot italian sausage. Cook the sausage, breaking it up into smaller pieces as you go, until fully cooked through. Using a slotted spoon, remove the sausage, place in a bowl, and set aside. Leave juices in the pan.",
        instructions3: "Lower the heat to medium and add in the onions. Saute for about 5 minutes until they begin to soften. Add the minced garlic and cook an additional minute. Add in the fire roasted tomatoes, the worcestershire sauce, and the herbs/spices: basil, oregano, thyme, salt, pepper, crushed red pepper flakes. Stir to combine. Add the sausage back in, the cooked rice, and the chicken broth. Stir to combine and allow the flavors to meld for 5 minutes while you prepare the peppers.",
        instructions4: "You can cut the peppers either horizontally or just cut a whole in the top and stuff them vertically. Either way you want to remove the stem, the seeds, and the white flesh from the inside using a pairing knife. Place the peppers in a baking dish, if they are having trouble standing shave a flat spot on the back of them with a pairing knife.",
        instructions5: "Using a spoon, stuff the peppers with the sausage mixture, top with cheese, and cover with foil. Place in the oven 30 minutes, peppers should be fork tender, remove the foil and low boil the cheese for 5 minutes or until lightly browned/melted. Remove from the oven and serve with frech parsley on top.",
        byWho:"By: Stephanie"
    },
];